TimeTraveller/Models/MyUsageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TimeTraveller.Models
{
    public class MyUsageViewModel
    {
    }
}

TimeTraveller/Controllers/CommonController.cs
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using TimeTraveller.Models;

namespace TimeTraveller.Controllers
{
    public class CommonController : Controller
    {
        public static string Fullname
        {
            get { return System.Web.HttpContext.Current.Session["BusinessID"].ToString(); }
            set { System.Web.HttpContext.Current.Session["BusinessID"] = value; }
        }

        // GET: Common
        public ActionResult UserDetails()
        {
            if (Session["Fullname"] == null)
            {
                var currentUserId = User.Identity.GetUserId();
                var manager =
                    new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var currentUser = manager.FindById(currentUserId);
                Session["Fullname"] = currentUser.FullName;
            }

            return PartialView("_UserDetails");
        }        
        
        // GET: Common
        public ActionResult MyUsage()
        {
            return PartialView("_MyUsage");
        }
    }
}

TimeTraveller/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Lapsody</title>
    <!-- BEGIN STYLESHEETS -->
    <script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=true&key=AIzaSyBuHZcHf8nfPe5tT0eUkWz15ZJNCZFGkrE"></script>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,600,700,800" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")

    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>

</head>
<body class="menubar-hoverable header-fixed">
<div id="dialog" class="card" style="display: none">
    <div class="card-head style-primary">
        <img style="width: 40px;" src="~/Content/images/lapsody.png"/>
        <b>&nbsp;Welcome to Lapsody</b>
    </div>

    <div class="card-body">
        <a href="@Url.Action("Login", "Account")">Register</a> and Join <b>Lapsody </b>to combat Carbon Emission and keep your Local Community Sustainable and Green
        <hr/>

        <div class="row">
            <div class="col-xs-4"></div>
            <div class="col-xs-4" style="margin: auto"><button onclick="closeDialog()" class="btn btn-flat">Close</button>
            </div>
            <div class="col-xs-4"></div>
        </div>

    </div>
</div>

<div id="pleaseWaitDialog" class="card" style="display: none">
    <div class="card-head style-primary">
        <img style="width: 40px;" src="~/Content/images/lapsody.png" />
        <b>&nbsp;Processing...</b>
    </div>

    <div class="card-body">
        Click on the Lighbulb to customise the appliances in your household. Lapsody will calculate your CO2 emmisions and overlay that data on Google Map.
        <hr />

        <div class="progress progress-striped active">
            <div class="bar" style="width: 100%;"></div>
        </div>

    </div>
</div>

<div id="dialogHint" class="card" style="display: none">
    <div class="card-head style-primary">
        <img style="width: 40px;" src="~/Content/images/lapsody.png" />
        <b>&nbsp;First Use</b>
    </div>

    <div class="card-body">
        Click on the Lighbulb to customise the appliances in your household. Lapsody will calculate your CO2 emmisions and overlay that data on Google Map.
        <hr />

        <div class="row">
            <div class="col-xs-4"></div>
            <div class="col-xs-4" style="margin: auto"><button onclick="closeDialogHint()" class="btn btn-flat">Close</button></div>
            <div class="col-xs-4"></div>
        </div>

    </div>
</div>


<!-- BEGIN HEADER-->
    <header id="header">
        <div class="headerbar">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="headerbar-left">
                <ul class="header-nav header-nav-options">
                    <li class="header-nav-brand">
                        <div class="brand-holder">
                            <a asp-controller="Home" asp-action="Index">
                                <span class="text-lg text-bold text-primary">Lapsody</span>
                            </a>
                        </div>
                    </li>
                    <li>
                        <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="headerbar-right">

                @if (Request.IsAuthenticated)
                {
                    Html.RenderAction("UserDetails", "Common");
                }

                @if (!Request.IsAuthenticated)
                {
                    <ul class="header-nav header-nav-toggle">
                        <li>
                            <a class="btn btn-icon-toggle btn-default" href="@Url.Action("Login", "Account")">
                                <i class="fa fa-lock"></i>
                            </a>
                        </li>
                    </ul>
                }

            </div>
        </div>
    </header>
    <!-- END HEADER-->
    <!-- BEGIN BASE-->
    <div id="base">

        <!-- BEGIN OFFCANVAS LEFT -->
        <div class="offcanvas">
        </div><!--end .offcanvas-->
        <!-- END OFFCANVAS LEFT -->
        <!-- BEGIN CONTENT-->
        <div id="content">

            <!-- BEGIN BLANK SECTION -->
            <section>
                @RenderBody()
            </section>

            <!-- BEGIN BLANK SECTION -->
        </div><!--end #content-->
        <!-- END CONTENT -->
        <!-- BEGIN MENUBAR-->
        <div id="menubar" class="menubar-scroll-panel">
            <div class="menubar-fixed-panel">
                <div>
                    <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>
                <div class="expanded">
                    <a href="@Url.Action("Index", "Home")" class="active">
                        <span class="text-lg text-bold text-primary ">LAPSODY</span>
                    </a>
                </div>
            </div>
            <div class="menubar-scroll-panel">

                <!-- BEGIN MAIN MENU -->
                <ul id="main-menu" class="gui-controls">

                    <!-- BEGIN DASHBOARD -->
                    <li>
                        <a href="@Url.Action("Index", "Home")" class="active">
                            <div class="gui-icon">
                                <i class="md md-home"></i>
                            </div>
                            <span class="title">Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/lapsodyAUS" target="_blank">
                            <div class="gui-icon">
                                <i class="fa fa-facebook-f"></i>
                            </div>
                            <span class="title">Facebook Page</span>
                        </a>
                    </li>
                    <!-- END DASHBOARD -->
                    @if (!Request.IsAuthenticated)
                    {
                    <!-- BEGIN DASHBOARD -->
                        <li>
                            <a href="@Url.Action("Login", "Account")">
                                <div class="gui-icon">
                                    <i class="md md-lock"></i>
                                </div>
                                <span class="title">Login</span>
                            </a>
                        </li>
                    <!--end /menu-li -->
                    <!-- END DASHBOARD -->
                    }
                    else
                    {

                    }

                </ul><!--end .main-menu -->
                <!-- END MAIN MENU -->

                <div class="menubar-foot-panel">
                    <small class="no-linebreak hidden-folded">
                        <span class="opacity-75">Copyright &copy; 2015</span> <strong>Time Travellers</strong>
                    </small>
                </div>
            </div><!--end .menubar-scroll-panel-->
        </div><!--end #menubar-->
        <!-- END MENUBAR -->
        <!-- BEGIN OFFCANVAS RIGHT -->
        @if (Request.IsAuthenticated)
        {
            Html.RenderAction("MyUsage", "Common");
        }
        <!-- END OFFCANVAS RIGHT -->

    </div><!--end #base-->
    <!-- END BASE -->
    @RenderSection("scripts", required: false)
</body>

</html>

TimeTraveller/Views/Shared/_MyUsage.cshtml
<div class="offcanvas">

    <!-- BEGIN OFFCANVAS SEARCH -->
    <div id="offcanvas-myusage" class="offcanvas-pane width-12">
        <div class="offcanvas-head">
            <header class="text-primary">My Household Appliances</header>
            <div class="offcanvas-tools">
                <a class="btn btn-icon-toggle btn-default-light pull-right" data-dismiss="offcanvas">
                    <i class="md md-close"></i>
                </a>
            </div>
        </div>
        <div class="offcanvas-body no-padding">
            <div class="card">
                <div class="card-header style-primary">

                </div>
                <div class="card-body">
                    <div id="entry" class="row">
                        <div class="col-xs-7" style="padding-left: 2px">
                            <form class="form">
                                <div class="form-group floating-label">
                                    <select id="cbxUsage" name="cbxUsage" class="form-control">
                                        <option value="">&nbsp;</option>
                                        <option value="Bedrooms">Bedrooms</option>
                                        <option value="Light Bulb">Light Bulb</option>
                                        <option value="Airconditioner">Airconditioner</option>
                                        <option value="Heater">Heater</option>
                                        <option value="Refrigerator">Refrigerator</option>
                                        <option value="Computer">Computer</option>
                                        <option value="Mobile Phones">Mobile Phones</option>
                                        <option value="Television">Television</option>
                                        <option value="Microwave Oven">Microwave Oven</option>
                                        <option value="Oven">Oven</option>
                                        <option value="Freezer">Freezer</option>
                                        <option value="Dishwasher">Dishwasher</option>
                                        <option value="Dryer">Dryer</option>
                                        <option value="Washing Machine">Washing Machine</option>
                                    </select>
                                    <label for="cbxUsage">Select Appliance</label>
                                </div>
                            </form>
                        </div>
                        <div class="col-xs-3">
                            <form class="form">
                                <div class="form-group floating-label">
                                    <select id="cbxQuantity" name="cbxQuantity" class="form-control">
                                        <option value="">&nbsp;</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                        <option value="9">9</option>
                                    </select>
                                    <label for="cbxQuantity">#</label>
                                </div>
                            </form>
                        </div>
                        <div class="col-xs-1">
                            <button type="button" onclick="addAppliance()" class="btn ink-reaction btn-raised btn-lg btn-primary">+</button>
                        </div>
                        <div class="col-xs-1"></div>
                    </div>
                    <hr/>
                    <ul class="list-comments scroll " id="usagelist">                        
                    </ul>
                </div>
            </div>
        </div><!--end .offcanvas-body -->

    </div><!--end .offcanvas-pane -->
    <!-- END OFFCANVAS SEARCH -->

</div><!--end .offcanvas-->

TimeTraveller/Views/Shared/_UserDetails.cshtml
<ul class="header-nav header-nav-options">
    <li class="dropdown">
        <a href="javascript:void(0);" class="btn btn-icon-toggle btn-default" data-toggle="dropdown">
            <i class="fa fa-clock-o"></i>
            <span id="currentYear" style="padding-right: 4px;">2014</span>
        </a>
        <ul class="dropdown-menu animation-expand">
            <li class="dropdown-header">Choose Timeline</li>
            <li class="dropdown-progress">
                <div class="card">
                    <div class="card-body">
                        <form class="form">
                            <div class="form-group">
                                <div id="datepicker"></div>
                            </div>
                        </form>
                    </div><!--end .card-body -->
                </div><!--end .card -->

            </li><!--end .dropdown-progress -->
        </ul><!--end .dropdown-menu -->
    </li><!--end .dropdown -->
</ul><!--end .header-nav-options -->

<ul class="header-nav header-nav-options">
    <li class="dropdown">
        <a href="javascript:void(0);" class="btn btn-icon-toggle btn-default" data-toggle="dropdown">
            <i class="fa fa-area-chart"></i>
        </a>
        <ul class="dropdown-menu animation-expand">
            <li class="dropdown-header">Toggle Map Overlay</li>
            <li class="dropdown-progress">
                <div class="checkbox checkbox-styled">
                    <label>
                        <input type="checkbox" value="" id="chkPowerStation" class="reportToggle">
                        <span><i class="fa fa-steam"></i>&nbsp;Power Stations</span>
                    </label>
                </div>
            </li><!--end .dropdown-progress -->
            <li class="dropdown-progress">
                <div class="checkbox checkbox-styled">
                    <label>
                        <input type="checkbox" value="" id="chkAircon" class="reportToggle">
                        <span><i class="fa fa-arrow-up"></i>&nbsp;Aircon Usage</span>
                    </label>
                </div>
            </li><!--end .dropdown-progress -->
            <li class="dropdown-progress">
                <div class="checkbox checkbox-styled">
                    <label>
                        <input type="checkbox" value="" id="chkHeater" class="reportToggle">
                        <span><i class="fa fa-arrow-down"></i>&nbsp;Heater Usage</span>
                    </label>
                </div>
            </li><!--end .dropdown-progress -->
            <li class="dropdown-progress">
                <div class="checkbox checkbox-styled">
                    <label>
                        <input type="checkbox" value="" id="chkWaterPollutionTurbidity" class="reportToggle">
                        <span><i class="fa fa-ship"></i>&nbsp;Water Pollution (Turbidity 2013-2014)</span>
                    </label>
                </div>
            </li><!--end .dropdown-progress -->
            <li class="dropdown-progress">
                <div class="checkbox checkbox-styled">
                    <label>
                        <input type="checkbox" value="" id="chkWaterPollutionChlorine" class="reportToggle">
                        <span><i class="fa fa-ship"></i>&nbsp;Water Pollution (Chlorine 2013-2014)</span>
                    </label>
                </div>
            </li><!--end .dropdown-progress -->
            <li class="dropdown-progress">
                <div class="checkbox checkbox-styled">
                    <label>
                        <input type="checkbox" value="" id="chkAirPollution" class="reportToggle">
                        <span><i class="fa fa-car"></i>&nbsp;Air Pollution (2010-2014)</span>
                    </label>
                </div>
            </li><!--end .dropdown-progress -->
        </ul><!--end .dropdown-menu -->
    </li><!--end .dropdown -->
</ul><!--end .header-nav-options -->



<ul class="header-nav header-nav-profile">
    <li class="dropdown">
        <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
            <img src="//lh3.googleusercontent.com/-TJc2-TVmW3M/AAAAAAAAAAI/AAAAAAAAAAA/XvAvQer9vQw/photo.jpg" alt=""/>
            <span class="profile-info">
                    @Session["Fullname"].ToString()
                </span>
        </a>
        <ul class="dropdown-menu animation-dock">
            <li class="dropdown-header">Config</li>
            <li><a href="@Url.Action("Index", "Manage")">My Profile</a></li>
            <li class="divider"></li>
            <li><a href="javascript:logOff();"><i class="fa fa-fw fa-power-off text-danger"></i> Logout</a></li>
        </ul><!--end .dropdown-menu -->
    </li><!--end .dropdown -->
</ul>

<ul class="header-nav header-nav-toggle">
    <li>
        <a class="btn btn-icon-toggle btn-default" href="#offcanvas-myusage" data-toggle="offcanvas" data-backdrop="false">
            <i class="fa fa-lightbulb-o"></i>
        </a>
    </li>
</ul>